### ISSUE TITLE
The constant EVRW_ST_CAT is not available in UnifiedPOS 1.15

### ISSUE THREAD

**Issue by kuniss** [kunif/OPOS-CCO#6]
Please check line 
https://github.com/kunif/OPOS-CCO/blob/707ffd4eaf15b283c5668a462251256cc7594829/Common/Opos/OposEvrw.h#L150

The mentioned constant is not defined at https://www.omg.org/spec/UPOS/1.15/PDF!

Is it maybe defined at 1.16? ... I did not check. Then the comment at that line is wrong.

In general: Please consider to inform us (project https://github.com/JavaPOSWorkingGroup/javapos-contracts) in case you are changing constant **_values_** here in your project as we want to be in sync with your constants in our Java project to get interoperability between OPOS and JavaPOS. ... Currently we are working on a [PR to get JavaPOS updated to UnifiedPOS 1.15](https://github.com/JavaPOSWorkingGroup/javapos-contracts/pull/13). Later on, we are planning to update to UnifiedPOS 1.16.

**Comment by kuniss** [comment]
Hey @kunif, did you saw my issue here?

**Comment by kunif** [comment]
I'm sorry, I haven't accessed GitHub for a while.
It's an issue I entered in the JIRA for UPOS 1.16 because the JIRA for UPOS 1.15 wasn't available.
At that time, UPOS 1.15 seemed to be in the Beta state from the outside, and UPOS 1.16 was under consideration for specifications.
Will the proposal be rejected after all?
Then it may not be reflected in UPOS 1.16.
However, as @kuniss has checked and pointed out the integrity of various other specifications, I also consider this to be an inconsistency / deficiency in the specifications I have pointed out.

By the way, isn't it better to delay the Java POS update after adding the 1.15.1 barcode type?

**Comment by kuniss** [comment]
@kunif, I will check whether there is an issue in the UnifiedPOS 1.16 JIRA project at OMG. I will come back to you here after checking.

Nevertheless, UnifiedPOS 1.15 is already released without that constant. So, it will not be added anymore at 1.15! I think, it would make sense at least to change the comment in your code... :smiley:

**Comment by kuniss** [comment]
> By the way, isn't it better to delay the Java POS update after adding the 1.15.1 barcode type?

What do you mean with that? Don't get it.

**Comment by kuniss** [comment]
Hi @kunif -San, 
Just checked the OMG JIRA project https://issues.omg.org/browse/UPOS1151 (in case you may have access to it) -- there are all the barcode extensions mentioned.
I guess, you are referring to that...

I'm not sure, but I guess, there will not be a 1.15.1 version. It will be all integrated into 1.16. But I may be wrong. I will try to clarify this at the next committee meeting.

**Comment by kuniss** [comment]
Hi @kunif -San, 
Just checked the OMG JIRA project https://issues.omg.org/browse/UPOS1151 (in case you may have access to it) -- there are all the barcode extensions mentioned.
I guess, you are referring to that... 

I'm not sure, but I guess, there will not be a 1.15.1 version. It will be all integrated into 1.16. But I may be wrong. I will try to clarify this at the next committee meeting.

**Comment by kuniss** [comment]
Hi @kunif -San,
just found your issue filed at https://issues.omg.org/browse/UPOS116_-3. 😄 

It is stated as resolved. However, I cannot figure out where the correction has been incorporated in...
I have to clarify this at the committee meeting next week!

But I'm going to close this issue here, because it is an issue at the UnifiedPOS specification, not this OPOS reference implementation.
